//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTServerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataM
    {
        public int DataId { get; set; }
        public int PM10 { get; set; }
        public int SensorId { get; set; }
        public string CoordX { get; set; }
        public string CoordY { get; set; }
        public string Date { get; set; }
    
        public virtual Sensor Sensor { get; set; }
    }
}
